yy: '{{ cycle.strftime("%y") }}'
ord: '{{ cycle.strftime("%j") }}'
hh: '{{ cycle.strftime("%H") }}'
fh: '{{ "%03d" % (leadtime.total_seconds() / 3600) }}'
to_link:
  /tmp/fsdemo/gribfile: /public/data/grids/gfs/0p25deg/grib2/{{ yy }}{{ ord }}{{ hh }}000{{ fh }}
