timevars:
  pyyyymmddhh: '{{ (cycle - user.cycle_int).strftime("%Y%m%d%H") }}'
  pyyyymmdd: '{{ (cycle - user.cycle_int).strftime("%Y%m%d") }}'
  yyyymmddhh: '{{ cycle.strftime("%Y%m%d%H") }}'
  yyyymmdd: '{{ cycle.strftime("%Y%m%d") }}'
  hh: '{{ cycle.strftime("%H") }}'
user:
  uw_training: /scratch3/BMC/wrfruc/cholt/uw_training_prep/uw_training
  expt_dir: /scratch3/BMC/wrfruc/cholt/uw_training_prep/expt4

  rrfs_workflow: /scratch3/BMC/wrfruc/cholt/rrfs_work/rrfs-workflow
  physics_suite: FV3_HRRR_gf
  cycle_int: !timedelta 1
  account: wrfruc
platform:
  scheduler: slurm
  fix: /scratch3/BMC/wrfruc/cholt/rrfs_work/FIX_RRFS
  fix_am: "{{ platform.fix }}/am"
  fix_lam: "{{ platform.fix }}/lam/RRFS_CONUS_13km_Lake_fracSV"
  input_data: /scratch3/BMC/wrfruc/cholt/rrfs_work/input_data
forecast_prod:
  fv3: &fv3_config
    diag_table:
      template_file: "{{ user.uw_training }}/parm/diag_table.{{ user.physics_suite }}"
      template_values:
        cres: C775
        starttime: !datetime "{{ cycle }}"
    domain: regional
    execution:
      batchargs:
        nodes: 4
        tasks_per_node: 21
        walltime: "00:45:00"
      envcmds:
        - ulimit -s unlimited
        - module use {{ user.rrfs_workflow }}/modulefiles
        - module load build_hera_intel
      executable: "{{ user.rrfs_workflow }}/exec/ufs_model"
      mpiargs:
        - "--export=ALL"
        - "--mem=0"
      mpicmd: srun
      threads: 1
    field_table:
      base_file: "{{ user.rrfs_workflow }}/parm/field_table.{{ user.physics_suite }}"
    files_to_copy: &files_to_copy
      INPUT/gfs_ctrl.nc: "{{ user.expt_dir }}/{{ timevars.yyyymmddhh }}/ics/gfs_ctrl.nc"
      INPUT/gfs_data.nc: "{{ user.expt_dir }}/{{ timevars.yyyymmddhh }}/ics/out.atm.tile7.nc"
      INPUT/sfc_data.nc: "{{ user.expt_dir }}/{{ timevars.yyyymmddhh }}/ics/out.sfc.tile7.nc"
      ufs.configure: "{{ user.uw_training }}/parm/ufs.configure"
      fd_ufs.yaml: "{{ user.uw_training }}/parm/fd_ufs.yaml"
    files_to_link:
      INPUT/grid_spec.nc: "{{ platform.fix_lam }}/C775_mosaic.halo3.nc"
      INPUT/grid.tile7.halo4.nc: "{{ platform.fix_lam }}/C775_grid.tile7.halo4.nc"
      INPUT/C775_grid.tile7.halo3.nc: "{{ platform.fix_lam }}/C775_grid.tile7.halo3.nc"
      INPUT/oro_data.nc: "{{ platform.fix_lam }}/C775_oro_data.tile7.halo0.nc"
      INPUT/oro_data.tile7.halo4.nc: "{{ platform.fix_lam }}/C775_oro_data.tile7.halo4.nc"
      INPUT/oro_data_ls.nc: "{{ platform.fix_lam }}/C775_oro_data_ls.tile7.halo0.nc"
      INPUT/oro_data_ss.nc: "{{ platform.fix_lam }}/C775_oro_data_ss.tile7.halo0.nc"
      aerosol.dat: '{{ platform.fix_am }}/global_climaeropac_global.txt'
      co2historicaldata_2010.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2010.txt'
      co2historicaldata_2011.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2011.txt'
      co2historicaldata_2012.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2012.txt'
      co2historicaldata_2013.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2013.txt'
      co2historicaldata_2014.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2014.txt'
      co2historicaldata_2015.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2015.txt'
      co2historicaldata_2016.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2016.txt'
      co2historicaldata_2017.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2017.txt'
      co2historicaldata_2018.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2018.txt'
      co2historicaldata_2019.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2019.txt'
      co2historicaldata_2020.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2020.txt'
      co2historicaldata_2021.txt: '{{ platform.fix_am }}/fix_co2_proj/global_co2historicaldata_2021.txt'
      co2historicaldata_glob.txt: '{{ platform.fix_am }}/global_co2historicaldata_glob.txt'
      co2monthlycyc.txt: '{{ platform.fix_am }}/co2monthlycyc.txt'
      global_h2oprdlos.f77: '{{ platform.fix_am }}/global_h2o_pltc.f77'
      global_albedo4.1x1.grb: '{{ platform.fix_am }}/global_albedo4.1x1.grb'
      global_zorclim.1x1.grb: '{{ platform.fix_am }}/global_zorclim.1x1.grb'
      global_tg3clim.2.6x1.5.grb: '{{ platform.fix_am }}/global_tg3clim.2.6x1.5.grb'
      sfc_emissivity_idx.txt: '{{ platform.fix_am }}/global_sfc_emissivity_idx.txt'
      solarconstant_noaa_an.txt: '{{ platform.fix_am }}/global_solarconstant_noaa_an.txt'
      global_o3prdlos.f77: '{{ platform.fix_am }}/ozprdlos_2015_new_sbuvO3_tclm15_nuchem.f77'
      CCN_ACTIVATE.BIN: '{{ platform.fix_am }}/CCN_ACTIVATE.BIN'
      freezeH2O.dat: '{{ platform.fix_am }}/freezeH2O.dat'
      qr_acr_qg.dat: '{{ platform.fix_am }}/qr_acr_qg.dat'
      qr_acr_qgV2.dat: '{{ platform.fix_am }}/qr_acr_qgV2.dat'
      qr_acr_qs.dat: '{{ platform.fix_am }}/qr_acr_qs.dat'
      qr_acr_qsV2.dat: '{{ platform.fix_am }}/qr_acr_qsV2.dat'
      Thompson_MP_MONTHLY_CLIMO.nc: '{{ platform.fix_am }}/Thompson_MP_MONTHLY_CLIMO.nc'
      <optics_file>: !glob '{{ platform.fix_am }}/optics_*.dat'
      <aeroclim_file>: !glob '{{ platform.fix_am }}/aeroclim.m*.nc'
    lateral_boundary_conditions: 
      interval_hours: 1
      offset: 0
      path: "{{ user.expt_dir }}/{{ timevars.yyyymmddhh }}/lbcs/{{ timevars.yyyymmddhh }}_{forecast_hour:03d}/gfs.bndy.nc"
    length: 3
    model_configure:
      update_values: &model_configure
        start_year: !int '{{ cycle.year }}'
        start_month: !int '{{ cycle.month }}'
        start_day: !int '{{ cycle.day }}'
        start_hour: !int '{{ cycle.hour }}'
        start_minute: !int '{{ cycle.minute }}'
        start_second: !int '{{ cycle.second }}'
        nhours_fcst: !int '{{ forecast_prod.fv3.length }}'
        fhrot: 0
        run_continue: false
        ens_sps: false
        dt_atmos: 120
        calendar: julian
        memuse_verbose: false
        restart_interval: 1
        output_1st_tstep_rst: false
        write_dopost: false
        ideflate: 0
        nbits: 0
        ichunk2d: -1
        jchunk2d: -1
        ichunk3d: -1
        jchunk3d: -1
        kchunk3d: -1
        itasks: 1
        quilting: true
        write_groups: 1
        write_tasks_per_group: 4
        num_files: 2
        filename_base: 'dyn phy'
        output_file: 'netcdf netcdf'
        output_fh: '1  -1'
        nsout: -1
        output_grid: lambert_conformal
        cen_lon: -97.5
        cen_lat: 38.5
        stdlat1: 38.5
        stdlat2: 38.5
        nx: 420
        ny: 252
        dx: 13000.0
        dy: 13000.0
    namelist:
      base_file: "{{ user.uw_training }}/parm/input.nml"
    rundir: "{{ user.expt_dir }}/{{ timevars.yyyymmddhh }}/fcst"
  platform: &driver_platform
    scheduler: "{{ platform.scheduler }}"
    account: "{{ user.account }}"
cycled_forecast:
  fv3:
    <<: *fv3_config
    files_to_copy:
      INPUT/fv_core.res.tile1.nc: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/RESTART/{{ timevars.yyyymmdd }}.{{ timevars.hh }}0000.fv_core.res.tile1.nc"
      INPUT/fv_srf_wnd.res.tile1.nc: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/RESTART/{{ timevars.yyyymmdd }}.{{ timevars.hh }}0000.fv_srf_wnd.res.tile1.nc"
      INPUT/fv_tracer.res.tile1.nc: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/RESTART/{{ timevars.yyyymmdd }}.{{ timevars.hh }}0000.fv_tracer.res.tile1.nc"
      INPUT/phy_data.nc: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/RESTART/{{ timevars.yyyymmdd }}.{{ timevars.hh }}0000.phy_data.nc"
      INPUT/sfc_data.nc: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/RESTART/{{ timevars.yyyymmdd }}.{{ timevars.hh }}0000.sfc_data.nc"
      INPUT/bk_coupler.res: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/RESTART/{{ timevars.yyyymmdd }}.{{ timevars.hh }}0000.coupler.res"
      INPUT/fv_core.res.nc: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/RESTART/{{ timevars.yyyymmdd }}.{{ timevars.hh }}0000.fv_core.res.nc"
      INPUT/gfs_ctrl.nc: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/fcst/INPUT/gfs_ctrl.nc"
      ufs.configure: "{{ user.uw_training }}/parm/ufs.configure"
      fd_ufs.yaml: "{{ user.uw_training }}/parm//fd_ufs.yaml"
    length: 3
    lateral_boundary_conditions:
      interval_hours: 1
      offset: 1
      path: "{{ user.expt_dir }}/{{ timevars.pyyyymmddhh }}/lbcs/{{ timevars.pyyyymmddhh }}_{forecast_hour:03d}/gfs.bndy.nc"
    namelist:
      base_file: "{{ user.uw_training }}/parm/input.nml"
      update_values:
        fv_core_nml:
          external_ic: false
          make_nh: false
          mountain: true
          na_init: 0
          nggps_ic: false
          warm_start: true
        gfs_physics_nml:
          lsoil: 9
    model_configure:
      update_values:
        <<: *model_configure
        run_continue: true
  platform:
    <<: *driver_platform
