user:
  expt_dir: /scratch3/BMC/wrfruc/uw_training/expt_dir
  uw_training: /scratch3/BMC/wrfruc/uw_training/uwtools_training
  rrfs_workflow: /scratch3/BMC/wrfruc/cholt/rrfs_work/rrfs-workflow
timevars:
  yyyymmddhh: '{{ cycle.strftime("%Y%m%d%H") }}'
  yyyymmdd: '{{ cycle.strftime("%Y%m%d") }}'
  hh: '{{ cycle.strftime("%H") }}'
  fff: '{{ "%03d" % (leadtime.total_seconds() / 3600) }}'
platform:
  fix: /scratch3/BMC/wrfruc/cholt/rrfs_work/FIX_RRFS
  fix_am: "{{ platform.fix }}/am"
  fix_lam: "{{ platform.fix }}/lam/RRFS_CONUS_13km_Lake_fracSV"
  input_data: /scratch3/BMC/wrfruc/cholt/rrfs_work/input_data
make_ics:
  # https://uwtools.readthedocs.io/en/main/sections/user_guide/yaml/components/chgres_cube.html
  chgres_cube:
    execution: &chgres_cube_execution
      batchargs:
        nodes: 1
        tasks_per_node: 20
        walltime: 00:30:00
      envcmds:
        - module use {{ user.rrfs_workflow }}/modulefiles
        - module load build_hera_intel
      executable: '{{ user.rrfs_workflow }}/exec/chgres_cube'
      mpiargs:
        - "--export=ALL"
      mpicmd: srun
    namelist:
      update_values:
        config: &chgres_cube_config
          convert_atm: true
          convert_nst: false
          convert_sfc: true
          cycle_day: !int "{{ (cycle + leadtime).strftime('%d') }}"
          cycle_hour: !int "{{ (cycle + leadtime).strftime('%H') }}"
          cycle_mon: !int "{{ (cycle + leadtime).strftime('%m') }}"
          data_dir_input_grid: "{{ platform.input_data }}/gfs"
          external_model: "GFS"
          fix_dir_target_grid: "{{ platform.fix_lam }}"
          grib2_file_input_grid: GFS-{{ timevars.yyyymmdd }}-{{ timevars.hh }}-f{{ timevars.fff }}.grib2
          halo_blend: 20
          halo_bndy: 4
          input_type: "grib2"
          lai_from_climo: true
          minmax_vgfrc_from_climo: true
          mosaic_file_target_grid: "{{ platform.fix_lam }}/C775_mosaic.halo4.nc"
          nsoill_out: 4
          orog_dir_target_grid: "{{ platform.fix_lam }}"
          orog_files_target_grid: "C775_oro_data.tile7.halo4.nc"
          regional: 1
          sotyp_from_climo: true
          tg3_from_soil: false
          varmap_file: "{{ user.rrfs_workflow }}/sorc/UFS_UTILS/parm/varmap_tables/GFSphys_var_map.txt"
          vcoord_file_target_grid: "{{ platform.fix_am }}/global_hyblev_fcst_rrfsL65.txt"
          vgfrc_from_climo: true
          vgtyp_from_climo: true
    rundir: '{{ user.expt_dir }}/{{ timevars.yyyymmddhh }}/ics'
  platform:
    account: wrfruc
    scheduler: slurm

#----------------------------
# MAKE LBCS config parameters
#-----------------------------
make_lbcs:
  # The entries in the chgres_cube: section follow along with the UW YAML, documented by uwtools:
  # https://uwtools.readthedocs.io/en/main/sections/user_guide/yaml/components/chgres_cube.html
  chgres_cube:
    execution:
      <<: *chgres_cube_execution
    namelist:
      update_values:
        config:
          <<: *chgres_cube_config
          regional: 2
    rundir: '{{ user.expt_dir }}/{{ timevars.yyyymmddhh }}/lbcs/{{ timevars.yyyymmddhh }}_{{ timevars.fff }}'
  platform:
    account: wrfruc
    scheduler: slurm
