defaults: &defaults
  10m_u_component_of_wind:
    level_type: heightAboveGround
    levels: [10]
    name: u_10m
  10m_v_component_of_wind:
    level_type: heightAboveGround
    levels: [10]
    name: v_10m
gfs:
  <<: *defaults
  10m_u_component_of_wind:
    name: UGRD
  10m_v_component_of_wind:
    name: VGRD
